package com.cx.client.client01;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.17
 * 2020-04-10T12:03:39.022+08:00
 * Generated source version: 3.1.17
 * 
 */
@WebService(targetNamespace = "http://service.cx.com/", name = "WeatherService")
@XmlSeeAlso({ObjectFactory.class})
public interface WeatherService {

    @WebMethod
    @RequestWrapper(localName = "queryWeather", targetNamespace = "http://service.cx.com/", className = "com.cx.client.client01.QueryWeather")
    @ResponseWrapper(localName = "queryWeatherResponse", targetNamespace = "http://service.cx.com/", className = "com.cx.client.client01.QueryWeatherResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String queryWeather(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );
}
