package com.cx.client.client01;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.17
 * 2020-04-10T18:28:18.261+08:00
 * Generated source version: 3.1.17
 * 
 */
@WebServiceClient(name = "WeatherServiceImplService", 
                  wsdlLocation = "http://localhost:8080/cxf/WeatherService?wsdl",
                  targetNamespace = "http://impl.service.cx.com/") 
public class WeatherServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.service.cx.com/", "WeatherServiceImplService");
    public final static QName WeatherServiceImplPort = new QName("http://impl.service.cx.com/", "WeatherServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/cxf/WeatherService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WeatherServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/cxf/WeatherService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WeatherServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WeatherServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WeatherServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public WeatherServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WeatherServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WeatherServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns WeatherService
     */
    @WebEndpoint(name = "WeatherServiceImplPort")
    public WeatherService getWeatherServiceImplPort() {
        return super.getPort(WeatherServiceImplPort, WeatherService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WeatherService
     */
    @WebEndpoint(name = "WeatherServiceImplPort")
    public WeatherService getWeatherServiceImplPort(WebServiceFeature... features) {
        return super.getPort(WeatherServiceImplPort, WeatherService.class, features);
    }

}
