
package com.cx.client.client01;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.17
 * 2020-04-10T12:05:00.237+08:00
 * Generated source version: 3.1.17
 * 
 */
public final class WeatherService_WeatherServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.service.cx.com/", "WeatherServiceImplService");

    private WeatherService_WeatherServiceImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = WeatherServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WeatherServiceImplService ss = new WeatherServiceImplService(wsdlURL, SERVICE_NAME);
        WeatherService port = ss.getWeatherServiceImplPort();  
        
        {
        System.out.println("Invoking queryWeather...");
        String _queryWeather_arg0 = "";
        String _queryWeather__return = port.queryWeather(_queryWeather_arg0);
        System.out.println("queryWeather.result=" + _queryWeather__return);


        }

        System.exit(0);
    }

}
